FROM node:12.8.1-alpine as client-build

RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
COPY package-lock.json /app
RUN npm install --quiet
COPY . /app
RUN npm run build

FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=client-build /app/build /usr/share/nginx/html
