version: "3.3"

services:
    client:
        container_name: geek-regime_dev_client
        build:
            context: ./client
            dockerfile: ./builder/Dockerfile.development
        command: npm start
        volumes:
            - ./client:/app
            - /app/node_modules # [1]
        stdin_open: true
        environment:
            - HOST=${CLIENT_HOST}
            - PORT=${CLIENT_PORT}
    server:
        container_name: geek-regime_dev_server
        build:
            context: ./server
            dockerfile: ./builder/Dockerfile.development
        command: npm run dev
        volumes:
            - ./server:/app
            - /app/node_modules
    postgres:
        container_name: geek-regime_dev_postgres
    redis:
        container_name: geek-regime_dev_redis

# [1]. A trick which allows to exlude the host's node_modules from the container's app directory
# after attaching shared volume: https://stackoverflow.com/a/37898591
