version: "3.3"

services:
    client:
        networks:
            - geek-regime
        depends_on:
            - server
            - postgres
            - redis
        ports:
            - ${CLIENT_PORT_EXTERNAL}:${CLIENT_PORT}
    server:
        networks:
            - geek-regime
        depends_on:
            - postgres
            - redis
        ports:
            - ${SERVER_PORT_EXTERNAL}:${SERVER_PORT}
        environment:
            - CACHE_STORE_HOST
            - CACHE_STORE_PORT
            - DATABASE_DB
            - DATABASE_DB_TEST
            - DATABASE_HOST
            - DATABASE_PASSWORD
            - DATABASE_PORT
            - DATABASE_USER
            - EMAIL_TRANSPORTER_API_KEY
            - GOOGLE_CLIENT_ID
            - GOOGLE_CLIENT_SECRET
            - GOOGLE_OAUTH_REDIRECT_URI
            - NODE_ENV
            - PROJECT_NAME_FULL
            - PROJECT_NAME_SHORT
            - SENDER_EMAIL
            - SERVER_PORT
            - SERVER_PORT_EXTERNAL
            - SESSION_NAME
            - SESSION_SECRET
            - YANDEX_CLIENT_ID
            - YANDEX_CLIENT_SECRET
    postgres:
        image: postgres:12.1-alpine
        restart: always
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - postgres-data:${DATABASE_DATA_PATH}
        networks:
            - geek-regime
        ports:
            - ${DATABASE_PORT_EXTERNAL}:${DATABASE_PORT}
        environment:
            - DATABASE_DB
            - DATABASE_DB_TEST
            - DATABASE_PASSWORD
            - DATABASE_USER
            - PGDATA=${DATABASE_DATA_PATH}
    redis:
        image: redis:5.0.7-alpine
        command: ["redis-server", "--appendonly", "yes"]
        volumes:
            - redis-data:/data
        networks:
            - geek-regime

networks:
    geek-regime:
        driver: bridge

volumes:
    postgres-data:
        driver: local
    redis-data:
        driver: local
