import CreatePostDto from "#types/post/CreatePostDto";
import UpdatePostDto from "#types/post/UpdatePostDto";

interface AutogeneratedData {
    userId?: number;
}

export type FakeDataOnCreate = CreatePostDto & AutogeneratedData;
export type FakeDataOnUpdate = UpdatePostDto & AutogeneratedData;
