import DataOnCreate from "#types/user/DataOnCreate";
import DataOnUpdate from "#types/user/DataOnUpdate";

interface AutogeneratedData {
    createdAt?: Date;
    hasPassword?: boolean;
    id?: number;
    updatedAt?: Date;
}

export type FakeDataOnCreate = DataOnCreate & AutogeneratedData;
export type FakeDataOnUpdate = DataOnUpdate & AutogeneratedData;
