export const ALREADY_EXISTS = "ALREADY_EXISTS";
export const EMAIL_OCCUPIED = "EMAIL_OCCUPIED";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const NO_USER_FOUND = "NO_USER_FOUND";
