export const ALREADY_EXISTS = "ALREADY_EXISTS";
export const FORBIDDEN = "FORBIDDEN";
export const INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const NOT_FOUND = "NOT_FOUND";
