#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$DATABASE_USER" --dbname "$DATABASE_DB" <<-EOSQL
	CREATE DATABASE $DATABASE_DB_TEST;
	GRANT ALL PRIVILEGES ON DATABASE $DATABASE_DB_TEST TO $DATABASE_USER;
EOSQL
