export const EMAIL_OCCUPIED = "EMAIL_OCCUPIED";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const NO_REQUIRED_PROPS = "NO_REQUIRED_PROPS";
export const NO_TABLE_CHOSEN = "NO_TABLE_CHOSEN";
export const NO_USER_FOUND = "NO_USER_FOUND";
