export const ALREADY_EXISTS = "ALREADY_EXISTS";
export const FORBIDDEN = "FORBIDDEN";
export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const INVALID_FILTER = "INVALID_FILTER";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const INVALID_PROPS = "INVALID_PROPS";
export const NOT_FOUND = "NOT_FOUND";
export const UNAUTHORIZED = "UNAUTHORIZED";
