const CREATE_POST_FAILURE = "CREATE_POST_FAILURE";
const CREATE_POST_START = "CREATE_POST_START";
const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
const DELETE_POST_FAILURE = "DELETE_POST_FAILURE";
const DELETE_POST_START = "DELETE_POST_START";
const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
const GET_POST_FAILURE = "GET_POST_FAILURE";
const GET_POST_START = "GET_POST_START";
const GET_POST_SUCCESS = "GET_POST_SUCCESS";
const GET_POSTS_FAILURE = "GET_POSTS_FAILURE";
const GET_POSTS_START = "GET_POSTS_START";
const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
const RESET_POST = "RESET_POST";
const RESET_POST_ERROR = "RESET_POST_ERROR";
const UPDATE_POST_FAILURE = "UPDATE_POST_FAILURE";
const UPDATE_POST_START = "UPDATE_POST_START";
const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";

export {
    CREATE_POST_FAILURE,
    CREATE_POST_START,
    CREATE_POST_SUCCESS,
    DELETE_POST_FAILURE,
    DELETE_POST_START,
    DELETE_POST_SUCCESS,
    GET_POST_FAILURE,
    GET_POST_START,
    GET_POST_SUCCESS,
    GET_POSTS_FAILURE,
    GET_POSTS_START,
    GET_POSTS_SUCCESS,
    RESET_POST,
    RESET_POST_ERROR,
    UPDATE_POST_FAILURE,
    UPDATE_POST_START,
    UPDATE_POST_SUCCESS
};
