export const ALREADY_EXISTS = "ALREADY_EXISTS";
export const INVALID_PASSWORD = "INVALID_PASSWORD";
export const NOT_FOUND = "NOT_FOUND";
export const UNAUTHORIZED = "UNAUTHORIZED";

export const INVALID_CREDENTIALS = "INVALID_CREDENTIALS";
export const INVALID_PROPS = "INVALID_PROPS";
export const NO_PROPS = "NO_PROPS";
