export default {
    CHECK_SESSION_FAILURE: "CHECK_SESSION_FAILURE",
    CHECK_SESSION_START: "CHECK_SESSION_START",
    CHECK_SESSION_SUCCESS: "CHECK_SESSION_SUCCESS",
    CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER",
    CLEAR_ERROR: "CLEAR_ERROR",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    SET_ERROR: "SET_CURRENT_USER_ERROR",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
    SIGN_IN_START: "SIGN_IN_START",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_OUT_FAILURE: "SIGN_OUT_FAILURE",
    SIGN_OUT_START: "SIGN_OUT_START",
    SIGN_OUT_SUCCESS: "SIGN_OUT_SUCCESS",
    SIGN_UP_FAILURE: "SIGN_UP_FAILURE",
    SIGN_UP_START: "SIGN_UP_START",
    SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS"
};
