export const HIDE_NOTIFICATION = "HIDE_NOTIFICATION";
export const SET_PENDING_OFF = "SET_PENDING_OFF";
export const SET_PENDING_ON = "SET_PENDING_ON";
export const SHOW_NOTIFICATION = "SHOW_NOTIFICATION";
