const CHECK_SESSION_FAILURE = "CHECK_SESSION_FAILURE";
const CHECK_SESSION_START = "CHECK_SESSION_START";
const CHECK_SESSION_SUCCESS = "CHECK_SESSION_SUCCESS";
const SIGN_IN_FAILURE = "SIGN_IN_FAILURE";
const SIGN_IN_START = "SIGN_IN_START";
const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
const SIGN_OUT_FAILURE = "SIGN_OUT_FAILURE";
const SIGN_OUT_START = "SIGN_OUT_START";
const SIGN_OUT_SUCCESS = "SIGN_OUT_SUCCESS";
const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
const SIGN_UP_START = "SIGN_UP_START";
const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
const UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE";
const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export {
    CHECK_SESSION_FAILURE,
    CHECK_SESSION_START,
    CHECK_SESSION_SUCCESS,
    SIGN_IN_FAILURE,
    SIGN_IN_START,
    SIGN_IN_SUCCESS,
    SIGN_OUT_FAILURE,
    SIGN_OUT_START,
    SIGN_OUT_SUCCESS,
    SIGN_UP_FAILURE,
    SIGN_UP_START,
    SIGN_UP_SUCCESS,
    UPDATE_PROFILE_FAILURE,
    UPDATE_PROFILE_START,
    UPDATE_PROFILE_SUCCESS
};
