export default {
    UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",
    UPDATE_PROFILE_RESET: "UPDATE_PROFILE_RESET",
    UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
    UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS"
};
