name: CD

on:
  repository_dispatch:
    types: [start-deploying]

jobs:
  deploy:
    name: "Deploy: ${{ github.event.client_payload.environment }}"
    if: ${{ github.event.client_payload.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.client_payload.environment }}
    steps:
    - name: Setup dependencies
      shell: bash
      run: |
        echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/} | tr / -)" >> $GITHUB_ENV
        echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $1}')" >> $GITHUB_ENV
        sudo apt-get update
        sudo apt-get install jq -y
    - name: Deliver to remote host
      env:
        DEPLOY_DIRECTORY: /home/${{secrets.DEPLOY_SERVER_USERNAME}}/environments
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        port: ${{ secrets.DEPLOY_SERVER_PORT }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        key: ${{ secrets.DEPLOY_SSH_KEY }}
        script: |
          while read -rd $'' line # [1]
          do
            if [[ $s != DEPLOY_* ]]; then
              export "$line"
            fi
          done < <(jq -r <<< '${{ toJSON(secrets) }}' 'to_entries|map("\(.key)=\(.value)\u0000")[]')

          cd ${{ env.DEPLOY_DIRECTORY }}

          if [ -d ${{ env.BRANCH_NAME }} ]; then
            cd ${{ env.BRANCH_NAME }}/${{ github.event.repository.name }}
            git pull
          else
            mkdir ${{ env.BRANCH_NAME }} && cd "$_"
            git clone ${{ secrets.REPO_SSH_URL }}
            cd ${{ github.event.repository.name }}
          fi

          git checkout ${{ env.BRANCH_NAME }}

          npm run prod:restart

# [1]. Export all available secrets as environment variables automatically (excluding those which
# start with "DEPLOY_" prefix). https://stackoverflow.com/a/48513046/10874193
